config/routes.rb
Abundant::Application.routes.draw do

  resources :material_quantity_labels

  resources :rigs

  resources :payments

  resources :material_uses

  resources :materials

  WepayRails.routes(self)

  resources :foundation_calculators

  resources :job_additions

  resources :day_crew_blocks

  resources :arrival_ranges

  resources :quarries

  devise_for :users, :controllers => {:registrations => "users"}

  match '/contacts/active_contacts' => "contacts#active_contacts"
  match '/contacts/dead_contacts' => "contacts#dead_contacts"
  match '/contacts/contact_active/:id' => "contacts#contact_active"
  match '/contacts/contact_dead/:id' => "contacts#contact_dead"
  match '/contacts/destroy/:id' => "contacts#destroy"
  match "/estimates/archive" => "estimates#index", :as => "estimates"
  post  '/estimates/email' => "estimates#email_estimate"
  match "/estimates/client_estimate/:token" => "estimates#client_estimate"
  match "/estimates/view_estimate/:token" => "estimates#view_estimate"
  match "/e/:token" => "estimates#client_estimate"
  match "/estimates/push_to_sold/:id/:type" => "estimates#push_to_sold"
  match "/estimates/off_level_to_show" => "estimates#off_level_to_show"
  post "/estimates/add_note" => "estimates#add_note"
  post "/estimates/pay_estimate" => "estimates#pay_estimate"
  match "/estimates/view_notes/:token" => "estimates#view_notes"
  match "/users/create" => "users#create"
  match "/schedule/(:action)" => "schedule"
  match 'jobs/foreman_print_modal/(:id)' => 'jobs#foreman_print_modal'
  match "/users/become/(:id)" => 'users#become'
  match "/reports/customers/:id" => "reports#customers"
  post  "/reports/search" => "reports#search"
  match "/library" => "document_library#index", as: "library"
  match "/elfinder" => "document_library#elfinder"
  match "/attach_files" => "document_library#attach_files", as: "attach_files"
  post  "/add_files_to_job" => "document_library#add_files_to_job"
  get   "/download_file/:id" => "document_library#download_file"
  namespace :purchase do
    match "/finalize" => 'finalize#index'
  end
  match "/reports" => "reports#index"

  resources :rock_pad_variables, :next_actions, :pad_jobs, :statuses, :foundations, :pad_sizes, :trucks, :rock_pad_variables, :jobs, :contacts, :campaigns, :locations, :schedule, :shed_companies, :crews, :content_data, :crew_dashboard, :users
  
  resources :jobs do
    member do
      get 'print'
      get 'print_modal'
      get 'edit_job_status'
      put 'update_job_status'
    end
  end

  match "/maps/google" => "maps#google"
  
  root :to => 'passthrough#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/quarry.rb
class Quarry < ActiveRecord::Base
	belongs_to :location
	after_create :geocode_address

  def geocode_address
    geo = Geokit::Geocoders::MultiGeocoder.geocode(address_oneline)
    errors.add(:address_1, "Could not Geocode address") if !geo.success
    raise "Geocode Error" if !geo.success
    if geo.success
      self.lat, self.lng = geo.lat,geo.lng 
      self.save
    end
  end

  def address_oneline
    [address_1,city,state,zip].reject{|f| f.blank? }.join(", ")
  end

  def address_block
    return "#{self.address_1 rescue ""}<br />#{self.address_2.nil? || self.address_2.empty? ? "" : "#{self.address_2 rescue ""}<br />" } #{self.city rescue ""}, #{self.state rescue ""} #{self.zip rescue ""}"
  end
end

app/controllers/quarries_controller.rb
class QuarriesController < ApplicationController
	before_filter :authenticate_user!
  # GET /quarries
  # GET /quarries.json
  def index
    @quarries = Quarry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quarries }
    end
  end

  # GET /quarries/1
  # GET /quarries/1.json
  def show
    @quarry = Quarry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quarry }
    end
  end

  # GET /quarries/new
  # GET /quarries/new.json
  def new
    @quarry = Quarry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quarry }
    end
  end

  # GET /quarries/1/edit
  def edit
    @quarry = Quarry.find(params[:id])
  end

  # POST /quarries
  # POST /quarries.json
  def create
    @quarry = Quarry.new(params[:quarry])

    respond_to do |format|
      if @quarry.save
        format.html { redirect_to @quarry, notice: 'Quarry was successfully created.' }
        format.json { render json: @quarry, status: :created, location: @quarry }
      else
        format.html { render action: "new" }
        format.json { render json: @quarry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quarries/1
  # PUT /quarries/1.json
  def update
    @quarry = Quarry.find(params[:id])

    respond_to do |format|
      if @quarry.update_attributes(params[:quarry])
        format.html { redirect_to @quarry, notice: 'Quarry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quarry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quarries/1
  # DELETE /quarries/1.json
  def destroy
    @quarry = Quarry.find(params[:id])
    @quarry.destroy

    respond_to do |format|
      format.html { redirect_to quarries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/quarries_helper.rb
module QuarriesHelper
end

app/views/quarries/_form.html.erb
<%= form_for(@quarry) do |f| %>
  <% if @quarry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quarry.errors.count, "error") %> prohibited this quarry from being saved:</h2>

      <ul>
      <% @quarry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quarries/edit.html.erb
<h1>Editing quarry</h1>

<%= render 'form' %>

<%= link_to 'Show', @quarry %> |
<%= link_to 'Back', quarries_path %>

app/views/quarries/index.html.erb
<h1>Listing quarries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lat</th>
    <th>Lng</th>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quarries.each do |quarry| %>
  <tr>
    <td><%= quarry.name %></td>
    <td><%= quarry.lat %></td>
    <td><%= quarry.lng %></td>
    <td><%= quarry.address_1 %></td>
    <td><%= quarry.address_2 %></td>
    <td><%= quarry.city %></td>
    <td><%= quarry.state %></td>
    <td><%= quarry.zip %></td>
    <td><%= link_to 'Show', quarry %></td>
    <td><%= link_to 'Edit', edit_quarry_path(quarry) %></td>
    <td><%= link_to 'Destroy', quarry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quarry', new_quarry_path %>

app/views/quarries/new.html.erb
<h1>New quarry</h1>

<%= render 'form' %>

<%= link_to 'Back', quarries_path %>

app/views/quarries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @quarry.name %>
</p>

<p>
  <b>Lat:</b>
  <%= @quarry.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @quarry.lng %>
</p>

<p>
  <b>Address 1:</b>
  <%= @quarry.address_1 %>
</p>

<p>
  <b>Address 2:</b>
  <%= @quarry.address_2 %>
</p>

<p>
  <b>City:</b>
  <%= @quarry.city %>
</p>

<p>
  <b>State:</b>
  <%= @quarry.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @quarry.zip %>
</p>


<%= link_to 'Edit', edit_quarry_path(@quarry) %> |
<%= link_to 'Back', quarries_path %>