config/routes.rb
Abundant::Application.routes.draw do

  resources :material_quantity_labels

  resources :rigs

  resources :payments

  resources :material_uses

  resources :materials

  WepayRails.routes(self)

  resources :foundation_calculators

  resources :job_additions

  resources :day_crew_blocks

  resources :arrival_ranges

  resources :quarries

  devise_for :users, :controllers => {:registrations => "users"}

  match '/contacts/active_contacts' => "contacts#active_contacts"
  match '/contacts/dead_contacts' => "contacts#dead_contacts"
  match '/contacts/contact_active/:id' => "contacts#contact_active"
  match '/contacts/contact_dead/:id' => "contacts#contact_dead"
  match '/contacts/destroy/:id' => "contacts#destroy"
  match "/estimates/archive" => "estimates#index", :as => "estimates"
  post  '/estimates/email' => "estimates#email_estimate"
  match "/estimates/client_estimate/:token" => "estimates#client_estimate"
  match "/estimates/view_estimate/:token" => "estimates#view_estimate"
  match "/e/:token" => "estimates#client_estimate"
  match "/estimates/push_to_sold/:id/:type" => "estimates#push_to_sold"
  match "/estimates/off_level_to_show" => "estimates#off_level_to_show"
  post "/estimates/add_note" => "estimates#add_note"
  post "/estimates/pay_estimate" => "estimates#pay_estimate"
  match "/estimates/view_notes/:token" => "estimates#view_notes"
  match "/users/create" => "users#create"
  match "/schedule/(:action)" => "schedule"
  match 'jobs/foreman_print_modal/(:id)' => 'jobs#foreman_print_modal'
  match "/users/become/(:id)" => 'users#become'
  match "/reports/customers/:id" => "reports#customers"
  post  "/reports/search" => "reports#search"
  match "/library" => "document_library#index", as: "library"
  match "/elfinder" => "document_library#elfinder"
  match "/attach_files" => "document_library#attach_files", as: "attach_files"
  post  "/add_files_to_job" => "document_library#add_files_to_job"
  get   "/download_file/:id" => "document_library#download_file"
  namespace :purchase do
    match "/finalize" => 'finalize#index'
  end
  match "/reports" => "reports#index"

  resources :rock_pad_variables, :next_actions, :pad_jobs, :statuses, :foundations, :pad_sizes, :trucks, :rock_pad_variables, :jobs, :contacts, :campaigns, :locations, :schedule, :shed_companies, :crews, :content_data, :crew_dashboard, :users
  
  resources :jobs do
    member do
      get 'print'
      get 'print_modal'
      get 'edit_job_status'
      put 'update_job_status'
    end
  end

  match "/maps/google" => "maps#google"
  
  root :to => 'passthrough#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/rock_pad_variable.rb
class RockPadVariable < ActiveRecord::Base
end

app/controllers/rock_pad_variables_controller.rb
class RockPadVariablesController < ApplicationController
  before_filter :authenticate_user!
  # GET /rock_pad_variables
  # GET /rock_pad_variables.xml
  def index
    # Cant do a SQL/Active Record :order in the find because of the name 'key'.  Reserved!
    @rock_pad_variables = RockPadVariable.find(:all).sort_by {|k| k.key }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rock_pad_variables }
    end
  end

  # GET /rock_pad_variables/1
  # GET /rock_pad_variables/1.xml
  def show
    @rock_pad_variable = RockPadVariable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rock_pad_variable }
    end
  end

  # GET /rock_pad_variables/new
  # GET /rock_pad_variables/new.xml
  def new
    @rock_pad_variable = RockPadVariable.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rock_pad_variable }
    end
  end

  # GET /rock_pad_variables/1/edit
  def edit
    @rock_pad_variable = RockPadVariable.find(params[:id])
  end

  # POST /rock_pad_variables
  # POST /rock_pad_variables.xml
  def create
    @rock_pad_variable = RockPadVariable.new(params[:rock_pad_variable])

    respond_to do |format|
      if @rock_pad_variable.save
        flash[:notice] = 'RockPadVariable was successfully created.'
        format.html { redirect_to(@rock_pad_variable) }
        format.xml  { render :xml => @rock_pad_variable, :status => :created, :location => @rock_pad_variable }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rock_pad_variable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rock_pad_variables/1
  # PUT /rock_pad_variables/1.xml
  def update
    @rock_pad_variable = RockPadVariable.find(params[:id])

    respond_to do |format|
      if @rock_pad_variable.update_attributes(params[:rock_pad_variable])
        flash[:notice] = 'RockPadVariable was successfully updated.'
        format.html { redirect_to(@rock_pad_variable) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rock_pad_variable.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rock_pad_variables/1
  # DELETE /rock_pad_variables/1.xml
  def destroy
    @rock_pad_variable = RockPadVariable.find(params[:id])
    @rock_pad_variable.destroy

    respond_to do |format|
      format.html { redirect_to(rock_pad_variables_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rock_pad_variables_helper.rb
module RockPadVariablesHelper
end

app/views/rock_pad_variables/edit.html.erb
<h1>Editing rock_pad_variable</h1>

<%= form_for(@rock_pad_variable) do |f| %>
  <% if @rock_pad_variable.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@rock_pad_variable.errors.count, "error") %> prohibited this post from being saved:</h2>

	      <ul>
	      <% @rock_pad_variable.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

  <p>
    <b><%= @rock_pad_variable.key %></b>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @rock_pad_variable %> |
<%= link_to 'Back', rock_pad_variables_path %>


<br /><br /><br /><br /><br /><br />
<%= link_to "Destroy", @rock_pad_variable, :confirm => 'Are you sure?', :method => :delete %>

app/views/rock_pad_variables/index.html.erb
<% title "Pad Variables" %>
<h1>Listing rock_pad_variables</h1>

<table class="table_liquid" cellspacing="0">
  <tr>
    <th>Key</th>
		<th>Description</th>
    <th>Value</th>
		<th>Actions</th>
  </tr>

<% @rock_pad_variables.each do |rock_pad_variable| %>
  <tr>
    <td><%=h rock_pad_variable.key %></td>
		<td><%=h rock_pad_variable.description %></td>
    <td><%=h rock_pad_variable.value %></td>
    <td><%= link_to 'Edit', edit_rock_pad_variable_path(rock_pad_variable) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Variable', new_rock_pad_variable_path, class: "button green-gradient icon-plus" %>

<br />
<br />
<br />
<br />

app/views/rock_pad_variables/new.html.erb
<h1>New rock_pad_variable</h1>

<%= form_for(@rock_pad_variable) do |f| %>
  <% if @rock_pad_variable.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@rock_pad_variable.errors.count, "error") %> prohibited this post from being saved:</h2>

	      <ul>
	      <% @rock_pad_variable.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

  <p>
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </p>
	<p>
		<%= f.label :description %><br />
		<%= f.text_area :description %><br />
	</p>
  <p>
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', rock_pad_variables_path %>

app/views/rock_pad_variables/show.html.erb
<p>
  <b>Key:</b>
  <%=h @rock_pad_variable.key %>
</p>

<p>
	<b>Description:</b>
	<%=h @rock_pad_variable.description %>
</p>

<p>
  <b>Value:</b>
  <%=h @rock_pad_variable.value %>
</p>


<%= link_to 'Edit', edit_rock_pad_variable_path(@rock_pad_variable) %> |
<%= link_to 'Back', rock_pad_variables_path %> |
<%= link_to "Destroy", @rock_pad_variable, :confirm => 'Are you sure?', :method => :delete %>