config/routes.rb
Abundant::Application.routes.draw do

  resources :material_quantity_labels

  resources :rigs

  resources :payments

  resources :material_uses

  resources :materials

  WepayRails.routes(self)

  resources :foundation_calculators

  resources :job_additions

  resources :day_crew_blocks

  resources :arrival_ranges

  resources :quarries

  devise_for :users, :controllers => {:registrations => "users"}

  match '/contacts/active_contacts' => "contacts#active_contacts"
  match '/contacts/dead_contacts' => "contacts#dead_contacts"
  match '/contacts/contact_active/:id' => "contacts#contact_active"
  match '/contacts/contact_dead/:id' => "contacts#contact_dead"
  match '/contacts/destroy/:id' => "contacts#destroy"
  match "/estimates/archive" => "estimates#index", :as => "estimates"
  post  '/estimates/email' => "estimates#email_estimate"
  match "/estimates/client_estimate/:token" => "estimates#client_estimate"
  match "/estimates/view_estimate/:token" => "estimates#view_estimate"
  match "/e/:token" => "estimates#client_estimate"
  match "/estimates/push_to_sold/:id/:type" => "estimates#push_to_sold"
  match "/estimates/off_level_to_show" => "estimates#off_level_to_show"
  post "/estimates/add_note" => "estimates#add_note"
  post "/estimates/pay_estimate" => "estimates#pay_estimate"
  match "/estimates/view_notes/:token" => "estimates#view_notes"
  match "/users/create" => "users#create"
  match "/schedule/(:action)" => "schedule"
  match 'jobs/foreman_print_modal/(:id)' => 'jobs#foreman_print_modal'
  match "/users/become/(:id)" => 'users#become'
  match "/reports/customers/:id" => "reports#customers"
  post  "/reports/search" => "reports#search"
  match "/library" => "document_library#index", as: "library"
  match "/elfinder" => "document_library#elfinder"
  match "/attach_files" => "document_library#attach_files", as: "attach_files"
  post  "/add_files_to_job" => "document_library#add_files_to_job"
  get   "/download_file/:id" => "document_library#download_file"
  namespace :purchase do
    match "/finalize" => 'finalize#index'
  end
  match "/reports" => "reports#index"

  resources :rock_pad_variables, :next_actions, :pad_jobs, :statuses, :foundations, :pad_sizes, :trucks, :rock_pad_variables, :jobs, :contacts, :campaigns, :locations, :schedule, :shed_companies, :crews, :content_data, :crew_dashboard, :users
  
  resources :jobs do
    member do
      get 'print'
      get 'print_modal'
      get 'edit_job_status'
      put 'update_job_status'
    end
  end

  match "/maps/google" => "maps#google"
  
  root :to => 'passthrough#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job_addition.rb
class JobAddition < ActiveRecord::Base
  belongs_to :job
  has_one :material_use
  
  before_destroy :update_job_price

  attr_accessible :addition_price_in_dollars, :addition_price_in_cents, :addition_description, :job_id

  def addition_price_in_dollars=(price)
    self.addition_price_in_cents = (price.to_f * 100).to_i
  end

  def addition_price_in_dollars
    self.addition_price_in_cents.to_f / 100
  end 

  def is_a_material_addition?
    material_use.present?
  end
  
  protected
  
  def update_job_price
    if self.job
      self.job.update_attribute(:price_in_cents, (self.job.price_in_cents - self.addition_price_in_cents))
    end
  end
end

app/controllers/job_additions_controller.rb
class JobAdditionsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @job_additions = JobAddition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_additions }
    end
  end

  def show
    @job_addition = JobAddition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_addition }
    end
  end

  def new
    @job_id = params[:job_id]
    @job_addition = JobAddition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_addition }
    end
  end

  def edit
    @job_addition = JobAddition.find(params[:id])
    @job_addition.addition_price_in_cents = @job_addition.addition_price_in_cents.to_f / 100
  end

  def create
    params[:job_addition][:addition_price_in_cents] = params[:job_addition][:addition_price_in_cents].to_f * 100
    @job_addition = JobAddition.new(params[:job_addition])

    respond_to do |format|
      if @job_addition.save
        format.html { redirect_to "/jobs/#{@job_addition.job_id}/edit", notice: 'Job addition was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    params[:job_addition][:addition_price_in_cents] = params[:job_addition][:addition_price_in_cents].to_f * 100 if params[:job_addition][:addition_price_in_cents].present?
    @job_addition = JobAddition.find(params[:id])

    respond_to do |format|
      if @job_addition.update_attributes(params[:job_addition])
        logger.debug("Here friend: #{@job_addition.inspect}")
        format.html { redirect_to "/jobs/#{@job_addition.job_id}/edit", notice: 'Job addition was successfully created.' }
      else
        format.html { redirect_to "/jobs/#{@job_addition.job_id}/edit" }
      end
    end
  end

  def destroy
    @job_addition = JobAddition.find(params[:id])
    @job_addition.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_additions_helper.rb
module JobAdditionsHelper
end

app/views/job_additions/_form.html.erb
<%= form_for(@job_addition) do |f| %>
  <% if @job_addition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_addition.errors.count, "error") %> prohibited this job_addition from being saved:</h2>

      <ul>
      <% @job_addition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :addition_price_in_cents, "Enter additional price (in dollars but without $, i.e. 250)" %><br />
    <%= f.text_field :addition_price_in_cents %>
  </div>
  <div class="field">
    <%= f.label :addition_description, "Description of Work" %><br />
    <%= f.text_area :addition_description %>
  </div>
	<%= f.hidden_field :job_id, :value => (@job_id || @job_addition.job_id) %>
  <div class="actions">
    <%= f.submit class: "button green-gradient glossy" %>
  </div>
<% end %>

app/views/job_additions/edit.html.erb
<h1>Editing job_addition</h1>

<%= render 'form' %>

<p style="margin: 10px 0;">
<%= link_to 'Back to Job', edit_job_path(@job_addition.job_id), class: "button white-gradient glossy icon-left" %>
</p>

app/views/job_additions/index.html.erb
<h1>Listing job_additions</h1>

<table>
  <tr>
    <th>Addition price in cents</th>
    <th>Addition description</th>
    <th>Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_additions.each do |job_addition| %>
  <tr>
    <td><%= job_addition.addition_price_in_cents %></td>
    <td><%= job_addition.addition_description %></td>
    <td><%= job_addition.job_id %></td>
    <td><%= link_to 'Show', job_addition %></td>
    <td><%= link_to 'Edit', edit_job_addition_path(job_addition) %></td>
    <td><%= link_to 'Destroy', job_addition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job addition', new_job_addition_path %>

app/views/job_additions/new.html.erb
<h1>New job_addition</h1>

<%= render 'form' %>

app/views/job_additions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Addition price in cents:</b>
  <%= @job_addition.addition_price_in_cents %>
</p>

<p>
  <b>Addition description:</b>
  <%= @job_addition.addition_description %>
</p>

<p>
  <b>Job:</b>
  <%= @job_addition.job_id %>
</p>


<%= link_to 'Edit', edit_job_addition_path(@job_addition) %> |
<%= link_to 'Back', job_additions_path %>