config/routes.rb
Abundant::Application.routes.draw do

  resources :material_quantity_labels

  resources :rigs

  resources :payments

  resources :material_uses

  resources :materials

  WepayRails.routes(self)

  resources :foundation_calculators

  resources :job_additions

  resources :day_crew_blocks

  resources :arrival_ranges

  resources :quarries

  devise_for :users, :controllers => {:registrations => "users"}

  match '/contacts/active_contacts' => "contacts#active_contacts"
  match '/contacts/dead_contacts' => "contacts#dead_contacts"
  match '/contacts/contact_active/:id' => "contacts#contact_active"
  match '/contacts/contact_dead/:id' => "contacts#contact_dead"
  match '/contacts/destroy/:id' => "contacts#destroy"
  match "/estimates/archive" => "estimates#index", :as => "estimates"
  post  '/estimates/email' => "estimates#email_estimate"
  match "/estimates/client_estimate/:token" => "estimates#client_estimate"
  match "/estimates/view_estimate/:token" => "estimates#view_estimate"
  match "/e/:token" => "estimates#client_estimate"
  match "/estimates/push_to_sold/:id/:type" => "estimates#push_to_sold"
  match "/estimates/off_level_to_show" => "estimates#off_level_to_show"
  post "/estimates/add_note" => "estimates#add_note"
  post "/estimates/pay_estimate" => "estimates#pay_estimate"
  match "/estimates/view_notes/:token" => "estimates#view_notes"
  match "/users/create" => "users#create"
  match "/schedule/(:action)" => "schedule"
  match 'jobs/foreman_print_modal/(:id)' => 'jobs#foreman_print_modal'
  match "/users/become/(:id)" => 'users#become'
  match "/reports/customers/:id" => "reports#customers"
  post  "/reports/search" => "reports#search"
  match "/library" => "document_library#index", as: "library"
  match "/elfinder" => "document_library#elfinder"
  match "/attach_files" => "document_library#attach_files", as: "attach_files"
  post  "/add_files_to_job" => "document_library#add_files_to_job"
  get   "/download_file/:id" => "document_library#download_file"
  namespace :purchase do
    match "/finalize" => 'finalize#index'
  end
  match "/reports" => "reports#index"

  resources :rock_pad_variables, :next_actions, :pad_jobs, :statuses, :foundations, :pad_sizes, :trucks, :rock_pad_variables, :jobs, :contacts, :campaigns, :locations, :schedule, :shed_companies, :crews, :content_data, :crew_dashboard, :users
  
  resources :jobs do
    member do
      get 'print'
      get 'print_modal'
      get 'edit_job_status'
      put 'update_job_status'
    end
  end

  match "/maps/google" => "maps#google"
  
  root :to => 'passthrough#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/day_crew_block.rb
class DayCrewBlock < ActiveRecord::Base
  belongs_to :crew

  attr_accessor :add_to_job

  after_save :persist_to_firebase
  before_destroy :remove_from_firebase

  private
  def persist_to_firebase
    begin
      FirebaseNotes.persist(self)
    rescue
      puts "\n\n*****ERROR saving this dayCrewBlock to Firebase*****\n\n"
    end
  end

  def remove_from_firebase
    begin
      FirebaseNotes.remove(self)
    rescue
      puts "\n\n*****ERROR removing dayCrewBlock to Firebase*****\n\n"
    end
  end

end

app/controllers/day_crew_blocks_controller.rb
class DayCrewBlocksController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /day_crew_blocks
  # GET /day_crew_blocks.json
  def index
    @day_crew_blocks = DayCrewBlock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @day_crew_blocks }
    end
  end

  # GET /day_crew_blocks/1
  # GET /day_crew_blocks/1.json
  def show
    @day_crew_block = DayCrewBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @day_crew_block }
    end
  end

  # GET /day_crew_blocks/new
  # GET /day_crew_blocks/new.json
  def new
    @day_crew_block = DayCrewBlock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @day_crew_block }
    end
  end

  # GET /day_crew_blocks/1/edit
  def edit
    @day_crew_block = DayCrewBlock.find(params[:id])
  end

  # POST /day_crew_blocks
  # POST /day_crew_blocks.json
  def create
    @day_crew_block = DayCrewBlock.new(params[:day_crew_block])
    result = if params[:day_crew_block] && !params[:day_crew_block][:add_to_job].blank?
      est = Estimate.find(params[:day_crew_block][:add_to_job])
      est.additional_notes = "" if est.additional_notes.nil?
      est.additional_notes += params[:day_crew_block][:reason].to_s + "\n"
      est.save
    else
      @day_crew_block.save
    end
    @crew = Crew.find_by_id( params[:day_crew_block][:crew_id])
    respond_to do |format|
      if result
        format.js #{ render "create", :locals => {:day => params[:day_crew_block][:day].to_date, :c => crew} }
        
      else
        format.html { render action: "new" }
        fformat.js { render js: @day_crew_block, status: :created, location: @day_crew_block }
      end
    end
  end

  # PUT /day_crew_blocks/1
  # PUT /day_crew_blocks/1.json
  def update
    @day_crew_block = DayCrewBlock.find(params[:id])

    respond_to do |format|
      params[:day_crew_block].delete :day
      if @day_crew_block.update_attributes(params[:day_crew_block])
        format.html { redirect_to :back, notice: 'Day crew block was successfully updated.' }
        format.json { render json: @day_crew_block }
      else
        format.html { render action: "edit" }
        format.json { render json: @day_crew_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_crew_blocks/1
  # DELETE /day_crew_blocks/1.json
  def destroy
    @day_crew_block = DayCrewBlock.find(params[:id])
    @day_crew_block.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/day_crew_blocks_helper.rb
module DayCrewBlocksHelper
end

app/views/day_crew_blocks/_form.html.erb
<%= form_for(@day_crew_block) do |f| %>
  <% if @day_crew_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_crew_block.errors.count, "error") %> prohibited this day_crew_block from being saved:</h2>

      <ul>
      <% @day_crew_block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :crew_id %><br />
    <%= f.number_field :crew_id %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.datetime_select :day %>
  </div>
  <div class="field">
    <%= f.label :contract_id %><br />
    <%= f.number_field :contract_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/day_crew_blocks/create.js.erb
$('#crew_<%= @crew.ordering%>').prepend($('<div class="crew_block_button closable" id="crew_block_<%= @day_crew_block.id %>"><div class="close_btn" data-id="<%= @day_crew_block.id %>"></div><span class="schedule_button_heading"><%=raw "<small>day blocked off for:</small><br />" if @day_crew_block.block_off %><b class="note-reason" data-id="<%= @day_crew_block.id %>"><%= @day_crew_block.reason %></b></span></div>')); 
$("#daycrewblock_<%=@crew.id%>").parent().find("form").slideToggle();
$("#loading").hide();

app/views/day_crew_blocks/destroy.js.erb
$('#crew_block_<%= "#{@day_crew_block.id}" %>').remove();

app/views/day_crew_blocks/edit.html.erb
<h1>Editing day_crew_block</h1>

<%= render 'form' %>

<%= link_to 'Show', @day_crew_block %> |
<%= link_to 'Back', day_crew_blocks_path %>

app/views/day_crew_blocks/index.html.erb
<h1>Listing day_crew_blocks</h1>

<table>
  <tr>
    <th>Crew</th>
    <th>Reason</th>
    <th>Day</th>
    <th>Contract</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @day_crew_blocks.each do |day_crew_block| %>
  <tr>
    <td><%= day_crew_block.crew_id %></td>
    <td><%= day_crew_block.reason %></td>
    <td><%= day_crew_block.day %></td>
    <td><%= day_crew_block.contract_id %></td>
    <td><%= link_to 'Show', day_crew_block %></td>
    <td><%= link_to 'Edit', edit_day_crew_block_path(day_crew_block) %></td>
    <td><%= link_to 'Destroy', day_crew_block, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day crew block', new_day_crew_block_path %>

app/views/day_crew_blocks/new.html.erb
<h1>New day_crew_block</h1>

<%= render 'form' %>

<%= link_to 'Back', day_crew_blocks_path %>

app/views/day_crew_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Crew:</b>
  <%= @day_crew_block.crew_id %>
</p>

<p>
  <b>Reason:</b>
  <%= @day_crew_block.reason %>
</p>

<p>
  <b>Day:</b>
  <%= @day_crew_block.day %>
</p>

<p>
  <b>Contract:</b>
  <%= @day_crew_block.contract_id %>
</p>


<%= link_to 'Edit', edit_day_crew_block_path(@day_crew_block) %> |
<%= link_to 'Back', day_crew_blocks_path %>